### ISSUE TITLE
Calculator option accepts decimals

### ISSUE THREAD

**Issue by ltjkoomen** [MariaAliceBorges/Calculeinard#1]
I am very upset that the calculator raises an error when I try to use the option `a` (or any character for that matter)

**Comment by MariaAliceBorges** [comment]
Hi handsome!

**Comment by MariaAliceBorges** [comment]
You're still handsome, even when you're wrong.

**Comment by MariaAliceBorges** [comment]
ok, I'll fix it tomorrow.
